version: '3'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server  --requirepass pass  --masterauth pass
    ports:
      - 6380:6379
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --masterauth pass  --requirepass pass
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379 --masterauth pass --requirepass pass